// src/components/ui/Button/Button.vue
<script setup lang="ts">
import { computed, ref } from 'vue';
import Flex from '@quizizz-ui/components/layouts/Flex/Flex.vue';
import Floating from '@quizizz-ui/components/layouts/Floating/Floating.vue';
import useButton from '@quizizz-ui/composables/useButton';
import type { IButton, PremiumIconSize } from '@quizizz-ui/components/ui/types';
import { SuperNotAllowedVariants } from '@quizizz-ui/components/ui/types';
import Icon from '@quizizz-ui/components/ui/Icon/Icon.vue';
import PremiumIcon from '@quizizz-ui/components/ui/PremiumIcon/PremiumIcon.vue';
import Text from '@quizizz-ui/components/primitives/Text/Text.vue';
import Box from '@quizizz-ui/components/primitives/Box/Box.vue';
import { classes } from '@quizizz-ui/utils/classes';
import useDebug from '@quizizz-ui/composables/useDebug';

const props = withDefaults(defineProps<IButton>(), {
  title: 'Button',
  size: 'md',
  variant: 'primary',
  lIconType: 'solid',
  tIconType: 'solid',
  disabled: false,
  isSuper: false,
  superVariant: 'superBox',
  loading: false,
  fullWidth: false,
  maxLength: -1,
});

const emit = defineEmits<{ (e: 'click', event: MouseEvent): void }>();

const wrapper = ref(null);

defineExpose({ wrapper });

const {
  bgColor,
  hoverBgColor,
  activeBgColor,
  borderColor,
  textColor,
  textSize,
  iconSize,
  padding,
  buttonHeight,
  textDecoration,
  textDecorationColor,
  hoverTextDecorationColor,
  activeTextDecorationColor,
} = useButton('Button', props);

const css = computed(() => {
  if (props.disabled) {
    return classes({
      bgColor: bgColor.value,
      hoverBgColor: hoverBgColor.value,
      padding: padding.value,
      height: buttonHeight.value,
    });
  }
  return classes({
    bgColor: bgColor.value,
    hoverBgColor: hoverBgColor.value,
    activeBgColor: activeBgColor.value,
    padding: padding.value,
    borderColor: borderColor.value,
    borderSize: '1',
    height: buttonHeight.value,
  });
});

const shouldShowSuperIcon = computed<boolean>(() => !SuperNotAllowedVariants.includes(props.variant) && props.isSuper);

const buttonTitle = computed<string>(() => {
  if (props.maxLength > 0) {
    return props.title.length > props.maxLength ? `${props.title.slice(0, props.maxLength)}..` : props.title;
  }
  return props.title;
});

const { debugClasses } = useDebug();
</script>

<template>
  <button
    ref="wrapper"
    :type="type"
    :aria-label="ariaLabel ? ariaLabel : title"
    :class="`${css} ${debugClasses} min-w-20 rounded flex items-center justify-center focus-visible:outline focus-visible:outline-4 focus-visible:outline-offset-2 shrink-0 focus-visible:outline-ds-lilac-500-40 ${disabled ? 'cursor-not-allowed' : 'cursor-pointer'} ${loading ? 'relative pointer-events-none' : ''} ${fullWidth ? 'w-full' : ''}`"
    :disabled="disabled"
    :data-testid="dataTestid"
    @click="(ev) => disabled || emit('click', ev)"
  >
    <Floating v-if="loading" position="center">
      <Icon
        type="regular"
        name="sync"
        :color="textColor"
        :size="iconSize"
        :fixedWidth="false"
        animate="spin"
      />
    </Floating>
    <Box :visibility="loading ? 'invisible' : 'visible'">
      <Flex align="center" justify="center" :gap="size === 'lg' ? '2' : '1'">
        <Icon
          v-if="Boolean(lIcon)"
          :type="lIconType"
          :name="lIcon ?? ''"
          :color="textColor"
          :size="iconSize"
          :fixedWidth="false"
        />
        <Text
          data-testid="button-text"
          :textVariant="textSize"
          :textColor="textColor"
          :textDecoration="textDecoration"
          :textDecorationColor="textDecorationColor"
          :hoverTextDecorationColor="hoverTextDecorationColor"
          :activeTextDecorationColor="activeTextDecorationColor"
          textUnderlineOffset="4"
          wrap="nowrap"
          select="none"
        >
          {{ buttonTitle }}
        </Text>
        <Icon
          v-if="Boolean(tIcon) && !isSuper"
          :type="tIconType"
          :name="tIcon ?? ''"
          :color="textColor"
          :size="iconSize"
          :fixedWidth="false"
        />
        <Box
          v-if="shouldShowSuperIcon"
        >
          <PremiumIcon :size="iconSize as PremiumIconSize" :variant="superVariant" />
        </Box>
      </Flex>
    </Box>
  </button>
</template>

// src/components/ui/Button/Button.tsx
import React, { forwardRef } from 'react';
import Flex from '../../layouts/Flex/Flex';
import Floating from '../../layouts/Floating/Floating';
import Icon from '../Icon/Icon';
// PremiumIcon is not yet converted, we'll comment out its usage for now
// import PremiumIcon from '../PremiumIcon/PremiumIcon';
import Text from '../../primitive/Text/Text';
import Box from '../../primitive/Box/Box';
import { SuperNotAllowedVariants } from './types';
import type { ButtonProps } from './types';

export const Button = forwardRef<HTMLButtonElement, ButtonProps>(
  (
    {
      title = 'Button',
      size = 'md',
      variant = 'primary',
      lIcon,
      lIconType = 'solid',
      tIcon,
      tIconType = 'solid',
      disabled = false,
      isSuper = false,
      superVariant = 'superBox',
      loading = false,
      fullWidth = false,
      maxLength = -1,
      type = 'button',
      ariaLabel,
      dataTestid,
      onClick,
    },
    ref
  ) => {
    // Since we're having issues with text and color props, let's use style for now
    const buttonStyle: React.CSSProperties = {
      padding: size === 'sm' ? '0.5rem' : size === 'md' ? '0.75rem' : '1rem',
      minHeight: size === 'sm' ? '2rem' : size === 'md' ? '2.5rem' : '3rem',
      minWidth: '5rem',
      backgroundColor: variant === 'primary' ? '#6B4EFF' : 
                      variant === 'secondary' ? '#FFFFFF' :
                      variant === 'danger' ? '#FF5151' : 
                      variant === 'outline' ? 'transparent' : '#F0F0F0',
      color: variant === 'primary' || variant === 'danger' ? 'white' : 
            variant === 'outline' ? '#6B4EFF' : '#333333',
      border: variant === 'outline' ? '1px solid #333333' : 'none',
      borderRadius: '4px',
      display: 'flex',
      alignItems: 'center',
      justifyContent: 'center',
      cursor: disabled ? 'not-allowed' : 'pointer',
      opacity: disabled ? 0.6 : 1,
      width: fullWidth ? '100%' : 'auto',
      fontSize: size === 'sm' ? '0.875rem' : size === 'md' ? '1rem' : '1.125rem',
      fontWeight: 600,
      transition: 'all 0.2s',
    };

    // This will override hover styles if we need them
    const hoverStyle: React.CSSProperties = {
      backgroundColor: variant === 'primary' ? '#5D43E5' : 
                      variant === 'secondary' ? '#F5F5F5' :
                      variant === 'danger' ? '#E54545' : 
                      variant === 'outline' ? 'rgba(107, 78, 255, 0.1)' : '#E5E5E5',
    };

    const iconSize = size === 'sm' ? '3' : size === 'md' ? '4' : '5';
    const iconColor = variant === 'primary' || variant === 'danger' ? 'light' : 'dark';
    
    // Re-add the shouldShowSuperIcon variable
    const shouldShowSuperIcon = !SuperNotAllowedVariants.includes(variant) && isSuper;

    const buttonTitle = maxLength > 0
      ? title.length > maxLength
        ? `${title.slice(0, maxLength)}..`
        : title
      : title;

    const handleClick = (event: React.MouseEvent<HTMLButtonElement>) => {
      if (disabled) return;
      onClick?.(event);
    };

    return (
      <button
        ref={ref}
        type={type}
        aria-label={ariaLabel || title}
        style={buttonStyle}
        disabled={disabled}
        data-testid={dataTestid}
        onClick={handleClick}
      >
        {loading && (
          <div style={{ position: 'absolute', display: 'flex', alignItems: 'center', justifyContent: 'center' }}>
            <span className="spinner" style={{ 
              display: 'inline-block', 
              width: '1rem', 
              height: '1rem', 
              borderRadius: '50%', 
              border: `2px solid ${iconColor === 'light' ? 'white' : '#333'}`,
              borderTopColor: 'transparent',
              animation: 'spin 1s linear infinite'
            }}></span>
          </div>
        )}
        <div style={{ visibility: loading ? 'hidden' : 'visible', display: 'flex', alignItems: 'center', gap: '0.5rem' }}>
          {lIcon && (
            <span className="icon" aria-hidden="true" style={{ marginRight: '0.25rem' }}>
              {/* Icon would go here */}
              {lIcon}
            </span>
          )}
          <span>{buttonTitle}</span>
          {tIcon && !isSuper && (
            <span className="icon" aria-hidden="true" style={{ marginLeft: '0.25rem' }}>
              {/* Icon would go here */}
              {tIcon}
            </span>
          )}
          {shouldShowSuperIcon && (
            <span className="premium-icon" aria-hidden="true" style={{ marginLeft: '0.25rem' }}>
              {/* Premium icon would go here */}
              ⭐
            </span>
          )}
        </div>
      </button>
    );
  }
);

Button.displayName = 'Button';

// Add some CSS for the spinner animation
const styleSheet = document.createElement('style');
styleSheet.textContent = `
  @keyframes spin {
    to { transform: rotate(360deg); }
  }
`;
document.head.appendChild(styleSheet);

export default Button;
