// src/components/primitive/Box/Box.tsx
import React from 'react';
import useCommon from '../../../hooks/useCommon';
import type { AlignSelf, CommonProps, ContentTag } from '../../../types';
import ContentTagComponent from '../../ui/ContentTagComponent/ContentTagComponent';

// Box props extend CommonProps
interface BoxProps extends CommonProps {
  self?: AlignSelf;
  fullWidth?: boolean;
  fullHeight?: boolean;
  fullSize?: boolean;
  as?: ContentTag;
  children?: React.ReactNode;
  className?: string;
}

const Box: React.FC<BoxProps> = ({
  as = 'div',
  grow,
  shrink,
  relative,
  basis,
  self,
  fullWidth,
  fullHeight,
  fullSize,
  children,
  className = '',
  dataTestid,
  group,
  ...rest
}) => {
  const { getCommonClasses } = useCommon();
  const css = getCommonClasses({
    grow,
    shrink,
    relative,
    basis,
    self,
    fullWidth,
    fullHeight,
    fullSize,
    ...rest
  });

  // For debugging purposes, implement a similar concept if needed
  const debugClasses = '';

  return (
    <ContentTagComponent
      as={as}
      className={`${css} ${group ? 'group' : ''} ${debugClasses} ${className}`}
      dataTestid={dataTestid}
    >
      {children}
    </ContentTagComponent>
  );
};

export default Box;

// src/components/primitive/Box/Box.vue
<script setup lang="ts">
import useCommon from '@quizizz-ui/composables/useCommon';
import type {
  AlignSelf, CommonProps, ContentTag,
} from '@quizizz-ui/types';
import ContentTagComponent from '@quizizz-ui/components/ui/ContentTagComponent/ContentTagComponent.vue';
import useDebug from '@quizizz-ui/composables/useDebug';

// Box props extend CommonProps
interface BoxProps extends CommonProps {
  self?: AlignSelf,
  fullWidth?: boolean,
  fullHeight?: boolean,
  fullSize?: boolean,
  as?: ContentTag,
};

const props = withDefaults(defineProps<BoxProps>(), {
  as: 'div',
  grow: undefined,
  shrink: undefined,
  relative: undefined,
  basis: undefined,
  fullWidth: undefined,
  fullHeight: undefined,
  fullSize: undefined,
});

const { css } = useCommon(props);
const { debugClasses } = useDebug();
</script>

<template>
  <ContentTagComponent :as="as" :class="`${css} ${group ? 'group' : ''} ${debugClasses}`" :data-testid="dataTestid">
    <slot />
  </ContentTagComponent>
</template>
